### ISSUE TITLE
What is the license for this library?

### ISSUE THREAD

**Issue by redonkulus** [beatgammit/deflate-js#3]
I did not see any mention of license in your README or package.json file. Please advise.

**Comment by Aaron-P** [comment]
It makes integral use of code from here (http://www.onicos.com/staff/iz/amuse/javascript/expert/) which is under the GPL (version 2 by the dates), which would make it almost certainly a derivative work.  I'm not a lawyer but it would most likely have to be licensed under GPLv2.

**Comment by beatgammit** [comment]
Yes, that's correct. This library is GPL (because of the included code), but any files not in lib are licensed under the MIT license.

Pull requests are welcome for replacing the GPL'd code with more liberally licensed code. I'll likely not get to it until I port this project over to Dart, which is on my TODO list.
